language: node_js

node_js:
    - "0.12"

before_script:
    - "npm install -g gulp"
    - "npm install -g webdriverio"
    - "npm install -g bower"
    - "bower i"
    - "gulp build"

branches:
    only:
        - gh-pages